# SPDX-FileCopyrightText: 2021-2024 SanderTheDragon <sanderthedragon@zoho.com>
#
# SPDX-License-Identifier: CC0-1.0

image: python:3.12-alpine

pages:
  stage: deploy
  before_script:
    - pip install -r $CI_PROJECT_DIR/requirements.txt
  script:
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - "public"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
